# Generated by Django 4.2.13 on 2024-07-02 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oaauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', related_query_name='reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informs', related_query_name='informs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inform',
            name='departments',
            field=models.ManyToManyField(related_name='informs', related_query_name='informs', to='oaauth.oadepartment'),
        ),
        migrations.AlterUniqueTogether(
            name='informread',
            unique_together={('inform', 'user')},
        ),
    ]
